// RobotBuilder Version: 1.0
//
// This file was generated by RobotBuilder. It contains sections of
// code that are automatically generated and assigned by robotbuilder.
// These sections will be updated in the future when you export to
// C++ from RobotBuilder. Do not put any code or make any change in
// the blocks indicating autogenerated code or it will be lost on an
// update. Deleting the comments indicating the section will prevent
// it from being updated in th future.
#include "OI.h"
// BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=INCLUDES
#include "SmartDashboard/SmartDashboard.h"
#include "Commands/DriveWithJoystick.h"
#include "Commands/RotateCCW.h"
#include "Commands/RotateCW.h"
    // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=INCLUDES
OI::OI() {
	// Process operator interface input here.
        // BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=CONSTRUCTORS
	attack3 = new Joystick(1);
	
	butRotateCCW = new JoystickButton(attack3, 4);
	butRotateCCW->WhileHeld(new RotateCCW());
	butRotateCW = new JoystickButton(attack3, 5);
	butRotateCW->WhileHeld(new RotateCW());
     
        // SmartDashboard Buttons
	SmartDashboard::PutData("DriveWithJoystick", new DriveWithJoystick());
	SmartDashboard::PutData("RotateCW", new RotateCW());
	SmartDashboard::PutData("RotateCCW", new RotateCCW());
    // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=CONSTRUCTORS
}
// BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=FUNCTIONS
Joystick* OI::getAttack3() {
	return attack3;
}
    // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=FUNCTIONS
